# Generated by Django 5.2.1 on 2025-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rate_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("currency", models.TextField()),
                ("price", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
