# Generated by Django 5.2.1 on 2025-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_app", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rate_data",
            constraint=models.UniqueConstraint(
                fields=("date", "currency"), name="unique_date_currency"
            ),
        ),
    ]
